url: "https://byemc.github.io/websitemaker" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

show_downloads: true
google_analytics: G-ZGPV9HGRFB
theme: jekyll-theme-modernist
